<!DOCTYPE html>
<html>
<head>
<title>Sapphire</title>
<style type="text/css">
    h1,h2 {
        font-family: normal Helvetica, Arial, sans-serif;
        text-align: center;
        color: #DDDDDD;
        margin: 0;
        padding: 0;
    }

    h1 {
        font-size: 100px;
        text-shadow: 0 -1px 0 #CCCCCC;
    }

    h2 {
        font-size: 30px;
        font-weight: normal;
        margin-top: 30px;
    }

    #container {
        position: fixed;
        top: 50%;
        left: 50%;
        width: 500px;
        height: 180px;
        margin-left: -250px;
        margin-top: -90px;
    }
</style>
</head>
<body>
    <div id="container">
        <h1>Sapphire</h1>
        <h2>PHP Development Kit</h2>
    </div>
</body>
</html>